Fixed a static build of libbz2 module

diff --git a/modules/libbz2/fix-paths.patch b/modules/libbz2/fix-paths.patch
--- a/modules/libbz2/fix-paths.patch
+++ b/modules/libbz2/fix-paths.patch
@@ -1,21 +1,19 @@
-diff -uNr bzip2-1.0.6/bzdiff bzip2-1.0.6.mod/bzdiff
---- bzip2-1.0.6/bzdiff	2007-01-03 04:00:55.000000000 +0200
-+++ bzip2-1.0.6.mod/bzdiff	2019-03-01 20:44:12.401418675 +0200
-@@ -37,7 +37,7 @@
- 	echo "Usage: $prog [${comp}_options] file [file]"
- 	exit 1
- fi
--tmp=`mktemp ${TMPDIR:-/tmp}/bzdiff.XXXXXXXXXX` || {
-+tmp=`mktemp ${TMPDIR:-@MAGISK_PREFIX@/tmp}/bzdiff.XXXXXXXXXX` || {
-       echo 'cannot create a temporary file' >&2
-       exit 1
- }
-@@ -56,7 +56,7 @@
-                         bzip2 -cdfq "$2" > $tmp
-                         bzip2 -cdfq "$1" | $comp $OPTIONS - $tmp
+--- ../src/bzdiff	2019-07-13 17:50:05.000000000 +0000
++++ ./bzdiff	2019-07-16 09:42:44.490220636 +0000
+@@ -49,14 +49,14 @@
+                 case "$2" in
+ 	        *.bz2)
+ 			F=`echo "$2" | sed 's|.*/||;s|.bz2$||'`
+-			tmp=`mktemp "${TMPDIR:-/tmp}"/bzdiff.XXXXXXXXXX` || {
++			tmp=`mktemp "${TMPDIR:-@MAGISK_PREFIX@/tmp}"/bzdiff.XXXXXXXXXX` || {
+ 			      echo 'cannot create a temporary file' >&2
+ 			      exit 1
+ 			}
+                         bzip2 -cdfq "$2" > "$tmp"
+                         bzip2 -cdfq "$1" | $comp $OPTIONS - "$tmp"
                          STAT="$?"
--			/bin/rm -f $tmp;;
-+			rm -f $tmp;;
+-			/bin/rm -f "$tmp";;
++			rm -f "$tmp";;
  
                  *)      bzip2 -cdfq "$1" | $comp $OPTIONS - "$2"
                          STAT="$?";;
